[package]
# AG: I wanted the "p2p" name for this crate but it was taken by https://crates.io/crates/p2p which we might even end up using.
name = "peers"
version = "0.1.0"

[lib]
name = "peers"
path = "peers.rs"
doctest = false

[dependencies]
common = { path = "../common" }
fomat-macros = "0.2"
futures = "0.1"
fxhash = "0.2"
gstuff = "0.5"
lazy_static = "1.2"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
unwrap = "1.2"
