[package]
name = "helpers"
version = "0.1.0"

[lib]
name = "helpers"
path = "helpers.rs"

[dependencies]
libc = "0.2"
hyper = "0.12"
hyper-tls = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
futures-cpupool = "0.1"