version: 1.0.{build}
shallow_clone: true
branches:
  only:
  - master
build_script:
- cmd: marketmaker_build_etomic.cmd
cache:
  - C:\.hunter
  - cpp-ethereum
  - marketmaker_depends

after_build:
  - 7z a mm-win.zip .\build_win64_release\iguana\exchanges\Release\marketmaker-mainnet.exe .\marketmaker_depends\curl\build_msvc_2015_win64\lib\Release\libcurl.dll .\marketmaker_depends\nanomsg\build_msvc_2015_win64\Release\nanomsg.dll

artifacts:
  - path: mm-win.zip
    name: marketmaker-mainnet

deploy:
  release: marketmaker-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: iabzoz73JgtOIyE/Nmz4a4XefmK+7pIeup+1Hunj4hGKrdfesFN+176DMApgfu8t
  artifact: marketmaker-mainnet
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true