version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: marketmaker_build_etomic.cmd
cache:
  - C:\.hunter
  - marketmaker_depends

after_build:
  - '7z a mm-win.zip
     .\target\debug\mm2.exe
     .\target\debug\*.dll
     "%WINDIR%\system32\msvcp140.dll"
     "%WINDIR%\system32\vcruntime140.dll"'

artifacts:
  - path: mm-win.zip
    name: marketmaker-mainnet

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: iabzoz73JgtOIyE/Nmz4a4XefmK+7pIeup+1Hunj4hGKrdfesFN+176DMApgfu8t
  artifact: marketmaker-mainnet
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false