[package]
name = "mm2"
version = "0.1.0"

# Waiting for https://doc.rust-lang.org/beta/cargo/reference/unstable.html#default-run to become stable.
#default-run = "mm2"

[[bin]]
name = "mm2"
path = "mm2src/mm2.rs"

[profile.dev]
# Enable light optimizations. We want a debuggable version but not a completely dumb one.
# Can override this with "set CARGO_BUILD_RUSTFLAGS=-C opt-level=0".
opt-level = 1

[features]
# Uncomment in order to enable ETOMIC builds by default:
default = ["etomic"]
etomic = ["etomicrs"]

[dependencies]
coins = { path = "mm2src/coins" }
common = { path = "mm2src/common" }
crc = "1.8"
crossbeam = "0.5"
dirs = "1.0"
duct = "0.11"
# `etomiclibrs` pulls https://github.com/briansmith/ring, to build which on Windows we need `perl` and `yasm` in the PATH.
# Download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe and rename to `yasm.exe`.
etomicrs = { path = "mm2src/etomic", optional = true }
fomat-macros = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
fxhash = "0.2"
gstuff = "0.5"
hex = "0.3.2"
hyper = "0.12"
lazy_static = "1.2"
libc = "0.2"
nix = "0.12"
peers = { path = "mm2src/peers" }
portfolio = { path = "mm2src/portfolio" }
rand = "0.5"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-core = "0.1.17"
unwrap = "1.2"
winapi = "0.3"

# ring 0.12 fails to build on Windows, this patch replaces it with ring 0.13.
[patch."https://github.com/paritytech/parity-common"]
parity-crypto = { git = "https://github.com/ArtemGr/parity-common" }
