[package]
name = "mm2"
version = "0.1.0"

[lib]
name = "mm2"
crate-type = ["staticlib"]
path = "iguana/exchanges/mm2.rs"

[dependencies]
# `etomiclibrs` pulls https://github.com/briansmith/ring, to build which on Windows we need `perl` and `yasm` in the PATH.
# Download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe and rename to `yasm.exe`.
etomiclibrs = { path = "iguana/exchanges/etomicswap" }

[build-dependencies]
bindgen = "0.37.4"

# ring 0.12 fails to build on Windows, this patch replaces it with ring 0.13.
[patch."https://github.com/paritytech/parity-common"]
parity-crypto = { git = "https://github.com/ArtemGr/parity-common" }
