[package]
name = "coins"
version = "0.1.0"
edition = "2018"

[lib]
name = "coins"
path = "coins.rs"
doctest = false

[dependencies]
base64 = "0.10.0"
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
byteorder = "1.2.2"
chain = { git = "https://github.com/artemii235/parity-bitcoin.git" }
common = { path = "../common" }
downcast-rs = "1.0.3"
fomat-macros = "0.2"
futures = "0.1"
gstuff = "0.5"
hex = "0.3.2"
hyper = "0.12"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.2"
libc = "0.2"
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rpc = { git = "https://github.com/artemii235/parity-bitcoin.git" }
script = { git = "https://github.com/artemii235/parity-bitcoin.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serialization = { git = "https://github.com/artemii235/parity-bitcoin.git" }
sha2 = "0.8"
tokio-timer = "0.1"
unwrap = "1.2"
