[package]
name = "mm2-libp2p"
version = "0.1.0"
authors = ["Artem Pikulin <ortgma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsecp256k1 = "0.3.5"
prost = "0.6.1"
rand = { version = "0.7", features = ["std"] }
sha2 = "0.9.0"

[build-dependencies]
prost-build = "0.6"