[package]
name = "etomiclibrs"
version = "0.1.0"
authors = ["Artem Pikulin <ortgma@gmail.com>"]

[lib]
name = "etomiclibrs"
path = "etomiclib.rs"

[dependencies]
ethcore-transaction = { git = "https://github.com/paritytech/parity.git" }
ethkey = { git = "https://github.com/paritytech/parity.git" }
rlp = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3.1"
web3 = { git = "https://github.com/ArtemGr/rust-web3" }
ethabi = { git = "https://github.com/ArtemGr/ethabi" }
hex = "0.3.2"
regex = "1"
libc = "0.2.42"
unwrap = "1.2.0"
